### ISSUE TITLE
Switch from DarkSky to another weather provider

### ISSUE THREAD

**Issue by bbernstein** [bbernstein/homebridge-snowsense#7]
Following up with [this issue](https://github.com/bbernstein/homebridge-snowsense/issues/8)

First find a quick solution, then we can look at more broad solutions for a substitute for DarkSky.

**Comment by bbernstein** [comment]
Using [OpenWeather](https://openweathermap.org/api)

Separating out the weather code from the rest so it will be easier to add more providers. Also removed need for other npm modules that were hardcoded for a single weather provider.

Add `provider` config item.

**Comment by nicoryan** [comment]
@bbernstein would it be possible to include the option to use API from Weatherflow tempest ?

**Comment by bbernstein** [comment]
I'd like to learn more about their API. It's a little hard not having one to test with. Same with WUnderground. I'd like to support it, but I don't have an API key to work with. Perhaps someone who has access or the device can help add those capabilities. I made this version easier to add new API's as it now supports both DarkSky and OpenWeather, so it's possible to add more providers.

> @bbernstein would it be possible to include the option to use API from Weatherflow tempest ?

**Comment by nicoryan** [comment]
@bbernstein is there a way that I can privately share with you my API key for WX Undergound? I can also share my Weatherflow Station ID. I am not a coder. So for me I have no idea how to implement any of this. But I am willing to help you in any way that I can.

**Comment by bbernstein** [comment]
Switched to OpenWeatherMap. This year I'm switching to the new UI config thing so probably won't be adding other weather api's yet. If needed, we can open a new issue for that. Closing this one.
